export type IWindowsMotherboard = {
  Product: string;
  Caption: string;
  Manufacturer: string;
  PartNumber: string | null;
  Name: string | null;
  Model: string | null;
  SerialNumber: string | null;
  ConfigOptions: string[] | null;
  CreationClassName: string | null;
  Depth: number | null;
  Description: string | null;
  Height: number | null;
  HostingBoard: boolean | null;
  HotSwappable: boolean | null;
  InstallDate: string | null;
  OtherIdentifyingInfo: string | null;
  PoweredOn: boolean | null;
  Removable: boolean | null;
  Replaceable: boolean | null;
  RequirementsDescription: string | null;
  RequiresDaughterBoard: boolean | null;
  Sku: string | null;
  SlotLayout: string | null;
  SpecialRequirements: boolean | null;
  Status: string | null;
  Tag: string | null;
  Version: string | null;
  Weight: number | null;
  Width: number | null;
};
